### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by gregsadetsky** [isaacdonis/acta-map#10]
- [x] rename project from 'config'
- [x] rename main app from 'pages'
- [X] refactor load_csv_file as management command
- [X] remove unnecessary reqs - jupiter, etc. -- try https://github.com/r1chardj0n3s/pip-check-reqs ?

**Comment by isaacdonis** [comment]
Done! For some reason the migrations are all still there, and referring to the old app name "pages". I hope that doesn't cause any issues if we update the models or add new ones.

Will close this issue once that question is cleared up.

**Comment by gregsadetsky** [comment]
great work! ah, and good point re: migrations. this miiight come back and bite us later if we deploy the project from scratch

but I wouldn't worry about it too much! vamanos :-)
