### ISSUE TITLE
delete mapbox credentials and create new ones that do not get shared on GitHub

### ISSUE THREAD

**Issue by isaacdonis** [isaacdonis/acta-map#22]

**Comment by gregsadetsky** [comment]
very small that mapbox public tokens i.e. those used in javascript are ok to share i.e. commit to code

They're shown/sent on the frontend so there's no way to hide them anyway

Happy to talk about it more but yeah. It's most probably ok here.!

**Comment by isaacdonis** [comment]
Oh! I was freaking out and about to take the site down haha!

**Comment by gregsadetsky** [comment]
All good & better to be safe!

The mapbox token can be restricted on mapbox.com to only work on certain domains, which is generally speaking a good idea - that way no one can use it to load frontend maps on other domains
