### ISSUE TITLE
look into simplifying map tech

### ISSUE THREAD

**Issue by gregsadetsky** [isaacdonis/acta-map#7]
look into protomaps - new york vectors only?

**Comment by isaacdonis** [comment]
Spent this morning going through the [Protomaps getting started documentation](https://docs.protomaps.com/guide/getting-started). Self-hosting seems like a really good idea! The area we're working with is really small.

One note about [Step 4 in the instructions ](https://docs.protomaps.com/guide/getting-started)- it doesn't work. I tried to drag `my_area.pmtiles` into the specified Drop Zone area several times, to no avail. Luckily there's [another Protomaps website](https://protomaps.github.io/PMTiles/#map=10.98/40.5951/-74.1578) that allows you to properly drag and view .pmtiles files.

One lingering question is that when we self-host, how can I be confident that the area visible on the website is constrained to the bounding box? When I upload to `https://protomaps.github.io/PMTiles/`, I can still scroll out to view the entire world... 🤔

**Comment by gregsadetsky** [comment]
heya! so you got a pmtiles files working then? that's great! how big is it out of curiosity?

re area visible -- we can limit which bounding box the map shows using leaflet/mapbox options i.e. whatever mapping javascript library we use, there's typically an option to restrict the zoom level/bounding box. and/or you can also subscribe to events (like someone zooming out) and if they zoom out too much or go out of bounds (i.e. outside of new york), you can bring them back into the fold :-)

for the pmtiles stuff to work, the easiest would be to setup a github pages on a separate repo (which is a bit easier than setting up a whole s3 bucket) and then we the pmtiles serving should work. happy to help with this and/or let me know if you want to take a stab at it!

**Comment by gregsadetsky** [comment]
heya! so you got a pmtiles files working then? that's great! how big is it out of curiosity?

re area visible -- we can limit which bounding box the map shows using leaflet/mapbox options i.e. whatever mapping javascript library we use, there's typically an option to restrict the zoom level/bounding box. and/or you can also subscribe to events (like someone zooming out) and if they zoom out too much or go out of bounds (i.e. outside of new york), you can bring them back into the fold :-)

for the pmtiles stuff to work, the easiest would be to setup a github pages on a separate repo (which is a bit easier than setting up a whole s3 bucket) and then we the pmtiles serving should work. happy to help with this and/or let me know if you want to take a stab at it!

**Comment by gregsadetsky** [comment]
Amazing! Using pmtiles, the client (browser) won't be downloading the whole file - which is the point of course.

Let me know how it goes, super exciting!

**Comment by isaacdonis** [comment]
I pushed some code to the development branch. Run the server and go to the Contact page of the app. You'll see 2 confusing things:

1. It _is_ loading the entire map, despite the file being 11MB
2. The other contents of the contact page, such as the text, aren't appearing

3. Unrelated, but also, I've been using a bounding box of just Staten Island to test the functionality. Once I move to the entire New York City, I'm pretty sure that file will be greater than Github's 25MB limit. This might justify something more serious, like an S3 bucket.

I'm still hacking at it and will probably figure it out, but I figured that raising something if I'm stuck on it for more than 16 working hours  is a good protocol to have.

**Comment by isaacdonis** [comment]
Pushed a new version of the map.

Re: previous comments ->
1. What's going on on the development branch isn't relevant anymore.
2. What's going on on the development branch isn't relevant anymore.
3. There seems to be an issue loading the tile that I have on GitHub pages. I knew it was too good to be true that I specifically cut out bounds of Staten Island so that it could be under 25MB, yet the entire NYC was loading on the map.

**Here is more context on point #3**:
When I open the Javascript pane and go to sources, there is an error that says "An error occurred trying to load this resource." when I click on the tile that I'm loading from my GitHub pages. I'll be investigating this issue. Regardless, though, the full tile of NYC will be larger than GitHub's allowed 25MB.

Regardless, from the user's perspective nothing is wrong! Super confusing (for now).

**Final thoughts**
I'll close this ticket once we are confident that we are hosting our own tile. This may necessitate another service like S3.

**Comment by gregsadetsky** [comment]
adding for later discussion/work - https://github.com/simonw/til/blob/main/gis/pmtiles.md

**Comment by isaacdonis** [comment]
oh! I was going through [these AWS instructions](https://docs.protomaps.com/deploy/aws#_4-cloudfront). The above link looks better. What do you think?

**Comment by gregsadetsky** [comment]
Yeah for sure it depends - we'll discuss but it depends on what the pmtiles file will include (roads and buildings or not), the final filesize, etc. We'll look at this together this Sunday, I think lots of good options!

**Comment by gregsadetsky** [comment]
decided to use mapbox.com after all for now, and can always switch out to another mapbox-like provider or self hosted tiles at any time in the future
